#!/bin/bash

curl -o qemu-arm-static https://github.com/multiarch/qemu-user-static/releases/download/v4.0.0/qemu-arm-static
curl -o qemu-aarch64-static https://github.com/multiarch/qemu-user-static/releases/download/v4.0.0/qemu-aarch64-static
chmod 777 qemu-arm-static qemu-aarch64-static