#!/bin/bash

curl --silent -o qemu-arm-static https://github.com/multiarch/qemu-user-static/releases/download/v4.0.0/qemu-arm-static
curl --silent -o qemu-aarch64-static https://github.com/multiarch/qemu-user-static/releases/download/v4.0.0/qemu-aarch64-static