#!/bin/bash

docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
             --build-arg VCS_REF=`git rev-parse --short HEAD` \
             --build-arg BASE_IMAGE=arm32v6/alpine \
             --build-arg QEMU=qemu-arm-static \
             -t $DOCKER_REPO:armhf .
docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
             --build-arg VCS_REF=`git rev-parse --short HEAD` \
             --build-arg BASE_IMAGE=arm64v8/alpine \
             --build-arg QEMU=qemu-aarch64-static \
             -t $DOCKER_REPO:aarch64 .
